global:
  imageTag: latest
  imagePullPolicy: Always
  imagePullSecrets:
    - name: ghcr-pull

demoAngular:
  replicaCount: 1

demoReact:
  replicaCount: 1

ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: widget-system.stortz.tech
      paths:
        - path: /angular(/|$)(.*)
          pathType: ImplementationSpecific
          service: demo-angular
        - path: /react(/|$)(.*)
          pathType: ImplementationSpecific
          service: demo-react
        - path: /()(.*)
          pathType: ImplementationSpecific
          service: demo-angular
