global:
  imageTag: prod

demoAngular:
  replicaCount: 3

demoReact:
  replicaCount: 3

ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: widget-system.int.stortz.tech
      paths:
        - path: /angular
          pathType: Prefix
          service: demo-angular
        - path: /react
          pathType: Prefix
          service: demo-react
        - path: /
          pathType: Prefix
          service: demo-angular
  tls:
    - secretName: widget-system-tls
      hosts:
        - widget-system.int.stortz.tech
